package com.splitmanager.domain.events;

public enum EventType {
    GROUP_CREATED,
    GROUP_SETTINGS_UPDATED,
    MEMBER_JOINED,
    MEMBER_APPROVED,
    MEMBER_REMOVED,
    INVITE_SENT,
    EXPENSE_CREATED,
    EXPENSE_UPDATED,
    EXPENSE_DELETED,
    SETTLEMENT_CREATED,
    SETTLEMENT_CONFIRMED,
    BALANCE_UPDATED
}
